Tests.EqualCheck("match 'd' in 'dog'", true, matchPattern("dog", "d"))
Tests.EqualCheck("match 'a' in 'apple'", true, matchPattern("apple", "a"))
Tests.EqualCheck("match 'x' in 'box'", true, matchPattern("box", "x"))
Tests.EqualCheck("match '1' in '123'", true, matchPattern("123", "1"))
Tests.EqualCheck("match 'n' in 'banana'", true, matchPattern("banana", "n"))
Tests.EqualCheck("do not match 'd' in 'cat'", false, matchPattern("cat", "d"))
Tests.EqualCheck("do not match 'z' in 'hello'", false, matchPattern("hello", "z"))
Tests.EqualCheck("case sensitivity - 'A' not in 'apple'", false, matchPattern("apple", "A"))
Tests.EqualCheck("empty line does not match 'a'", false, matchPattern("", "a"))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("dog", ""))
