Tests.EqualCheck("match character in positive group", true, matchPattern("apple", "[abc]"))
Tests.EqualCheck("match another character in positive group", true, matchPattern("cab", "[abc]"))
Tests.EqualCheck("match vowel in word", true, matchPattern("cat", "[aeiou]"))
Tests.EqualCheck("match digits inside group", true, matchPattern("item3", "[123]"))
Tests.EqualCheck("do not match when group characters are absent", false, matchPattern("dog", "[abc]"))
Tests.EqualCheck("do not match when no vowels present", false, matchPattern("rhythm", "[aeiou]"))
Tests.EqualCheck("do not match empty line with character group", false, matchPattern("", "[abc]"))
Tests.EqualCheck("still match \\w pattern", true, matchPattern("apple", `\w`))
Tests.EqualCheck("still match \\d pattern", true, matchPattern("apple1", `\d`))
Tests.EqualCheck("still match literal character", true, matchPattern("dog", "d"))
Tests.EqualCheck("still do not match missing literal character", false, matchPattern("cat", "d"))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("anything", ""))
