Tests.EqualCheck("match digit followed by word characters", true, matchPattern("I have 3 dogs", `\d \w\w\w\w`))
Tests.EqualCheck("match character group followed by digit", true, matchPattern("item_a1_end", `[abc]\d`))
Tests.EqualCheck("match negative group followed by digit", true, matchPattern("code_z9", `[^abc]\d`))
Tests.EqualCheck("match three consecutive word characters", true, matchPattern("apple", `\w\w\w`))
Tests.EqualCheck("match three consecutive digits", true, matchPattern("item_123_test", `\d\d\d`))
Tests.EqualCheck("do not match when digit is absent before word chars", false, matchPattern("I have no dogs", `\d \w\w\w\w`))
Tests.EqualCheck("do not match when character is not in positive group", false, matchPattern("item_d1_end", `[abc]\d`))
Tests.EqualCheck("do not match when character is in excluded group", false, matchPattern("code_a9", `[^abc]\d`))
Tests.EqualCheck("do not match pattern longer than line", false, matchPattern("hi", `\w\w\w\w`))
Tests.EqualCheck("do not match on empty line", false, matchPattern("", `\d \w`))
Tests.EqualCheck("still match single digit", true, matchPattern("apple1", `\d`))
Tests.EqualCheck("still match single word character", true, matchPattern("apple", `\w`))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("anything", ""))
