Tests.EqualCheck("match word character (letters)", true, matchPattern("apple", `\w`))
Tests.EqualCheck("match word character (digits)", true, matchPattern("123", `\w`))
Tests.EqualCheck("match word character (underscore)", true, matchPattern("_", `\w`))
Tests.EqualCheck("match word character in punctuation string", true, matchPattern("$!a?", `\w`))
Tests.EqualCheck("do not match symbols only", false, matchPattern("$!?", `\w`))
Tests.EqualCheck("do not match spaces and punctuation", false, matchPattern("   !@#", `\w`))
Tests.EqualCheck("do not match empty line with \\w", false, matchPattern("", `\w`))
Tests.EqualCheck("still match \\d pattern", true, matchPattern("apple1", `\d`))
Tests.EqualCheck("still do not match missing \\d", false, matchPattern("apple", `\d`))
Tests.EqualCheck("still match literal character", true, matchPattern("dog", "d"))
Tests.EqualCheck("still do not match missing literal character", false, matchPattern("cat", "d"))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("anything", ""))
