Tests.EqualCheck("match character not in group", true, matchPattern("dog", "[^abc]"))
Tests.EqualCheck("match character not in group for mixed string", true, matchPattern("apple", "[^abc]"))
Tests.EqualCheck("match consonant when vowels excluded", true, matchPattern("cat", "[^aeiou]"))
Tests.EqualCheck("do not match when all characters are in excluded group", false, matchPattern("cab", "[^abc]"))
Tests.EqualCheck("do not match single character in excluded group", false, matchPattern("c", "[^abc]"))
Tests.EqualCheck("do not match when all characters are excluded vowels", false, matchPattern("aeio", "[^aeiou]"))
Tests.EqualCheck("do not match empty line with negative group", false, matchPattern("", "[^abc]"))
Tests.EqualCheck("still match positive group", true, matchPattern("apple", "[abc]"))
Tests.EqualCheck("still match \\w pattern", true, matchPattern("apple", `\w`))
Tests.EqualCheck("still match \\d pattern", true, matchPattern("apple1", `\d`))
Tests.EqualCheck("still match literal character", true, matchPattern("dog", "d"))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("anything", ""))
