Tests.EqualCheck("match digit at end of line", true, matchPattern("apple1", `\d`))
Tests.EqualCheck("match digit at start of line", true, matchPattern("99bottles", `\d`))
Tests.EqualCheck("match digit in middle of line", true, matchPattern("item_42_end", `\d`))
Tests.EqualCheck("match single digit string", true, matchPattern("0", `\d`))
Tests.EqualCheck("do not match line with no digits", false, matchPattern("apple", `\d`))
Tests.EqualCheck("do not match empty line with \\d", false, matchPattern("", `\d`))
Tests.EqualCheck("still match literal character", true, matchPattern("dog", "d"))
Tests.EqualCheck("still do not match missing literal character", false, matchPattern("cat", "d"))
Tests.EqualCheck("empty pattern matches any line", true, matchPattern("anything", ""))
